# Generated by Django 5.0.6 on 2024-07-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YourModelName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('item_id', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True, null=True)),
                ('frp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bu', models.CharField(blank=True, max_length=255, null=True)),
                ('period', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
                ('ids', models.CharField(blank=True, max_length=255, null=True)),
                ('as_field', models.CharField(blank=True, max_length=255, null=True)),
                ('ssp', models.CharField(blank=True, max_length=255, null=True)),
                ('cwc', models.CharField(blank=True, max_length=255, null=True)),
                ('edw', models.CharField(blank=True, max_length=255, null=True)),
                ('lkr', models.CharField(blank=True, max_length=255, null=True)),
                ('bt', models.CharField(blank=True, max_length=255, null=True)),
                ('krz', models.CharField(blank=True, max_length=255, null=True)),
                ('mwb', models.CharField(blank=True, max_length=255, null=True)),
                ('elab', models.CharField(blank=True, max_length=255, null=True)),
                ('byn', models.CharField(blank=True, max_length=255, null=True)),
                ('idsbel', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
