# Generated by Django 5.0.6 on 2024-07-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CeMapng',
            fields=[
                ('sid', models.AutoField(db_column='SID', primary_key=True, serialize=False)),
                ('jusrisdiction', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Jusrisdiction', max_length=10, null=True)),
                ('src_type', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=30, null=True)),
                ('src_tblnm', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=500, null=True)),
                ('tgt_tblnm', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=500, null=True)),
                ('tgt_tblcols', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', null=True)),
                ('mapng_nm', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=500, null=True)),
                ('mpngtxt', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', null=True)),
                ('insrt_timestamp', models.DateTimeField(blank=True, db_column='insrt_TIMESTAMP', null=True)),
            ],
            options={
                'db_table': 'ce_mapng',
                'managed': False,
            },
        ),
    ]
