from django.urls import path
from .import views


urlpatterns = [
    # path('usa_g/', views.usa_guide_list, name='usa_guide_list'),
    
    path('usa_guide_list/', views.usa_guide_list, name='usa_guide_list'),
    path('bal_guide_list/', views.bal_guide_list, name='bal_guide_list'),
    path('azrb_guide_list/', views.azrb_guide_list, name='azrb_guide_list'),
    path('idsbjm_guide_list/', views.idsbjm_guide_list, name='idsbjm_guide_list'),
    path('kz_guide_list/', views.kz_guide_list, name='kz_guide_list'),
    path('uz_guide_list/', views.uz_guide_list, name='uz_guide_list'),
    path('inventory/', views.fetch_inventory, name='inventory'),
    path('balance/', views.fetch_Balance, name='balance'),
    path('COGS/', views.fetch_COGS, name='COGS'),
    path('INFO1/', views.fetch_INFO1, name='INFO1'),
    path('INFO2/', views.fetch_INFO2, name='INFO2'),
    path('marketing/', views.fetch_marketing, name='marketing'),
    path('reclass/', views.fetch_reclass, name='reclass'),
    path('sales/', views.fetch_sales, name='sales'),
    path('purchases/', views.fetch_purchases, name='purchases'),
    path('inv_balance_purchase/', views.fetch_invbalancepurchase, name='invbalpur'),
    path('other_asset_liabilities/', views.fetch_otherassetliabilities, name='otherassetliabilities'),
    path('lease_roll_forward/', views.fetch_leaserollforward, name='leaserollforward'),
    path('capex_1_v/', views.fetch_capex1v, name='capex1v'),
    path('capex_2_v/', views.fetch_capex2v, name='capex2v'),
    path('fin_cost_view/', views.fetch_fincostview, name='fincostview'),
    path('01/', views.fetch_01, name='01'),
    path('taxes_head/', views.fetch_taxeshead, name='taxeshead'),
    path('bcv/', views.fetch_bcv, name='bcv'),
    path('consult/', views.fetch_consult, name='consult'),
    path('mon/', views.fetch_mon, name='mon'),
    path('0ev/', views.fetch_0ev, name='0ev'),
    path('sfv/', views.fetch_sfv, name='sfv'),
    path('tcv/', views.fetch_tcv, name='tcv'),
    path('tiv/', views.fetch_tiv, name='tiv'),
    path('l0_v12/', views.fetch_l0V12, name='l0v12'),
    path('11_ic_v1/', views.fetch_11IcV1, name='11icv1'),
    path('quantity_1_v/', views.fetch_quantity1v, name='quantity1v'),
    path('quantity_2_v/', views.fetch_quantity2v, name='quantity2v'),
    path('gross_discount_1_v/', views.fetch_grossdiscount1v, name='grossdiscount1v'),
    path('gross_discount_2_v/', views.fetch_grossdiscount2v, name='grossdiscount2v'),
    path('gross_revenue_1_v/', views.fetch_grossrevenue1v, name='grossrevenue1v'),
    path('gross_revenue_2_v/', views.fetch_grossrevenue2v, name='grossrevenue2v'),
    path('cogs_1_v/', views.fetch_cogs1v, name='cogs1v'),
    path('cogs_2_v/', views.fetch_cogs2v, name='cogs2v'),
    path('cogs_custom/', views.fetch_cogscustom, name='cogscustom'),
    path('cogs_mon/', views.fetch_cogsmon, name='cogsmon'),
    path('cogs_log/', views.fetch_coglog, name='coglog'),
    path('log1/', views.fetch_log1, name='log1'),
    path('ct_us_pl_6_log_2/', views.fetch_ct_us_pl_6_log_2, name='ctuspl6log2'),
    path('ct_us_pnl_9_forex_v/', views.fetch_ct_us_pnl_9_forex_v, name='ctuspnl9forexv'),
    path('ct_cwc_pl_0_v12/', views.fetch_ct_cwc_pl_0_v12, name='ctcwcpl0v12'),
    path('ct_us_bs_2_inv_balance_date_at_v/', views.fetch_ct_us_bs_2_inv_balance_date_at_v, name='ctusbs2invbalancedateatv'),
    path('ctusbs2invbalancepurchase/', views.fetch_ct_us_bs_2_inv_balance_purchase, name='ctusbs2invbalancepurchase'),
    path('ctuspnl0v/', views.fetch_ct_us_pnl_0_v, name='ctuspnl0v'),
    path('csv/generate/', views.generate_csv, name='generate_csv')
]