# Generated by Django 5.0.6 on 2024-05-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CE_US_IC_AP_AR_Reclass_v',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reknr', models.IntegerField()),
                ('GLDesc', models.CharField(max_length=1000)),
                ('Account', models.CharField(max_length=1000)),
                ('value', models.IntegerField()),
                ('ReclassGL', models.IntegerField()),
            ],
            options={
                'db_table': 'CE_US_IC_AP_AR_Reclass_v',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CE_US_IC_cogs_cust_v',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(max_length=10)),
                ('credit', models.IntegerField(max_length=100)),
            ],
            options={
                'db_table': 'CE_US_IC_cogs_cust_v',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CE_US_IC_Inventory_v',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Year', models.CharField(max_length=4)),
                ('month', models.CharField(max_length=10)),
                ('GLAccount', models.CharField(max_length=100)),
                ('Actual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Quantity', models.IntegerField()),
                ('sku', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'CE_US_IC_Inventory_v',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CE_US_IC_marketing_v',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField()),
                ('cost_unit', models.IntegerField()),
                ('value', models.IntegerField()),
                ('item', models.CharField(max_length=1000)),
                ('fs_line', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'CE_US_IC_marketing_v',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CE_US_IC_Purchases_v',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('SKU', models.CharField(max_length=1000)),
                ('bottles', models.IntegerField()),
                ('Liters', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'CE_US_IC_Purchases_v',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CE_US_IC_Sales_v',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('reknr', models.IntegerField()),
                ('GLAccount', models.CharField(max_length=1000)),
                ('Gross_Revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Bottles', models.IntegerField()),
                ('SKU', models.CharField(max_length=1000)),
                ('Liters', models.DecimalField(decimal_places=2, max_digits=10)),
                ('COGS', models.IntegerField()),
                ('cogs_customs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cogs_logistics', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Gross_discount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'CE_US_IC_Sales_v',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CE_US_IC_Trial_Balance_v',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=10)),
                ('ledger_Account', models.CharField(max_length=100)),
                ('val', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Corection', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Mapping', models.CharField(max_length=100)),
                ('fsline', models.CharField(max_length=100)),
                ('GA_Group', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'CE_US_IC_Trial_Balance_v',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CE_US_INFO1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SKU', models.CharField(max_length=1000)),
                ('RevGL', models.CharField(max_length=1000)),
                ('COGSGL', models.IntegerField()),
                ('InvGL', models.IntegerField()),
                ('BrandGroup', models.CharField(max_length=1000)),
                ('Vol', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'CE_US_INFO1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CE_US_INFO2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.IntegerField()),
                ('Groups', models.CharField(max_length=1000)),
                ('Item', models.CharField(max_length=1000)),
                ('FS_line', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'CE_US_INFO2',
                'managed': False,
            },
        ),
    ]
