# Generated by Django 5.0.6 on 2024-06-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_standalone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bs2InvBalancePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('val', models.CharField(blank=True, max_length=1000)),
                ('bottles', models.FloatField(blank=True)),
                ('month', models.CharField(blank=True, max_length=2)),
            ],
            options={
                'db_table': 'BS_2_inv_Balance_purchase',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bs3OtherAssetsLiabilitiesV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('subcategory', models.CharField(blank=True, max_length=100, null=True)),
                ('monyy', models.CharField(blank=True, db_column='MonYY', max_length=6, null=True)),
                ('runningtotal', models.FloatField(blank=True, db_column='RunningTotal', null=True)),
            ],
            options={
                'db_table': 'BS_3_Other_assets_liabilities_V',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bs4LeaseRollForwardV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, db_column='Category', max_length=255, null=True)),
                ('subcategory', models.CharField(blank=True, db_column='Subcategory', max_length=255, null=True)),
                ('total', models.FloatField(blank=True, db_column='Total', null=True)),
                ('monyy', models.CharField(blank=True, db_column='MonYY', max_length=6, null=True)),
                ('date2', models.DateField(blank=True, db_column='Date2', null=True)),
            ],
            options={
                'db_table': 'BS_4_Lease_roll_forward_V',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bs6Capex1V',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('date2', models.DateField(blank=True, db_column='Date2', null=True)),
            ],
            options={
                'db_table': 'BS_6_CAPEX_1_V',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bs6Capex2V',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('date2', models.DateField(blank=True, db_column='Date2', null=True)),
            ],
            options={
                'db_table': 'BS_6_CAPEX_2_V',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CeUsFinCostView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_cost_heads', models.CharField(blank=True, db_column='Fin_cost_Heads', max_length=100, null=True)),
                ('monyy', models.CharField(blank=True, db_column='MonYY', max_length=6, null=True)),
                ('total', models.FloatField(blank=True, db_column='Total', null=True)),
            ],
            options={
                'db_table': 'CE_US_Fin_Cost_View',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CeUsIcApArReclassV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reknr', models.IntegerField(blank=True, null=True)),
                ('gldesc', models.CharField(blank=True, db_column='GLDesc', max_length=100, null=True)),
                ('account', models.CharField(blank=True, db_column='Account', max_length=50, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('reclassgl', models.IntegerField(blank=True, db_column='ReclassGL', null=True)),
            ],
            options={
                'db_table': 'CE_US_IC_AP_AR_Reclass_v',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CeUsIcBs01',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('subcategory', models.CharField(blank=True, max_length=100, null=True)),
                ('monyy', models.DateField(blank=True, db_column='MonYY', null=True)),
                ('total', models.FloatField(blank=True, db_column='Total', null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('runningtotal', models.FloatField(blank=True, db_column='RunningTotal', null=True)),
            ],
            options={
                'db_table': 'CE_US_IC_BS_0_1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CeUsIcBs7TaxesHeadsV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, db_column='Category', max_length=100, null=True)),
                ('subcategory', models.CharField(blank=True, db_column='SubCategory', max_length=100, null=True)),
                ('monyy', models.CharField(blank=True, max_length=6, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('date2', models.DateField(blank=True, db_column='Date2', null=True)),
                ('total', models.FloatField(blank=True, db_column='Total', null=True)),
            ],
            options={
                'db_table': 'CE_US_IC_BS_7_Taxes_heads_V',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CeUsIcGnaBcV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpt_name', models.CharField(blank=True, db_column='Dpt_name', max_length=100, null=True)),
                ('monyy', models.CharField(blank=True, db_column='MonYY', max_length=6, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CE_US_IC_GNA_BC_v',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CeUsIcGnaConsultV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpt_name', models.CharField(blank=True, db_column='Dpt_name', max_length=100, null=True)),
                ('monyy', models.DateField(blank=True, db_column='MonYY', null=True)),
                ('total', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CE_US_IC_GNA_Consult_v',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CeUsIcGnaMon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(blank=True, db_column='Expense_type', max_length=100, null=True)),
                ('monyy', models.DateField(blank=True, db_column='Monyy', null=True)),
                ('total', models.FloatField(blank=True, db_column='Total', null=True)),
            ],
            options={
                'db_table': 'CE_US_IC_GNA_Mon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CeUsIcGnaOeV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpt_name', models.CharField(blank=True, db_column='Dpt_name', max_length=100, null=True)),
                ('monyy', models.DateField(blank=True, db_column='MonYY', null=True)),
                ('total', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CE_US_IC_GNA_OE_v',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CeUsIcGnaSfV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpt_name', models.CharField(blank=True, db_column='Dpt_name', max_length=100, null=True)),
                ('monyy', models.DateField(blank=True, db_column='MonYY', null=True)),
                ('total', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CE_US_IC_GNA_SF_v',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CeUsIcGnaTcV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpt_name', models.CharField(blank=True, db_column='Dpt_name', max_length=100, null=True)),
                ('monyy', models.DateField(blank=True, db_column='MonYY', null=True)),
                ('total', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CE_US_IC_GNA_TC_v',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CeUsIcGnaTiV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpt_name', models.CharField(blank=True, db_column='Dpt_name', max_length=100, null=True)),
                ('monyy', models.DateField(blank=True, db_column='MonYY', null=True)),
                ('total', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CE_US_IC_GNA_TI_v',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CtCwcPl0V12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, db_column='GROUP', max_length=50, null=True)),
                ('cluster', models.CharField(blank=True, db_column='Cluster', max_length=50, null=True)),
                ('entity', models.CharField(blank=True, db_column='Entity', max_length=50, null=True)),
                ('sid', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('date2', models.DateField(blank=True, db_column='Date2', null=True)),
                ('monyy', models.CharField(blank=True, max_length=6, null=True)),
                ('cat', models.CharField(blank=True, max_length=50, null=True)),
                ('sub_cat', models.CharField(blank=True, db_column='Sub_cat', max_length=200, null=True)),
                ('val', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CT_cwc_PL_0_V1_2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CtUsBs2InvBalanceDateAtV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('val', models.CharField(blank=True, max_length=1000, null=True)),
                ('insrt_timestamp', models.DateTimeField(blank=True, db_column='insrt_TIMESTAMP', null=True)),
                ('year', models.CharField(blank=True, db_column='Year', max_length=100, null=True)),
                ('month', models.CharField(blank=True, max_length=2, null=True)),
                ('glaccount', models.CharField(blank=True, db_column='GLAccount', max_length=113, null=True)),
                ('actual', models.FloatField(blank=True, db_column='Actual', null=True)),
                ('quantity', models.FloatField(blank=True, db_column='Quantity', null=True)),
                ('sku', models.CharField(blank=True, max_length=50, null=True)),
                ('runningtotalquantity', models.FloatField(blank=True, db_column='RunningTotalQuantity', null=True)),
                ('runningtotalactual', models.FloatField(blank=True, db_column='RunningTotalActual', null=True)),
            ],
            options={
                'db_table': 'ct_US_BS_2_inv_Balance_date_at_v',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CtUsBs2InvBalancePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('val', models.CharField(blank=True, max_length=1000, null=True)),
                ('bottles', models.FloatField(blank=True, null=True)),
                ('month', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'ct_US_BS_2_inv_Balance_purchase',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CtUsPl0V12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, db_column='GROUP', max_length=50, null=True)),
                ('cluster', models.CharField(blank=True, db_column='Cluster', max_length=50, null=True)),
                ('entity', models.CharField(blank=True, db_column='Entity', max_length=50, null=True)),
                ('sid', models.IntegerField(blank=True, null=True)),
                ('cid', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('date2', models.DateField(blank=True, db_column='Date2', null=True)),
                ('monyy', models.CharField(blank=True, max_length=6, null=True)),
                ('cat', models.CharField(blank=True, max_length=50, null=True)),
                ('sub_cat', models.CharField(blank=True, db_column='Sub_cat', max_length=200, null=True)),
                ('val', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CT_US_PL_0_V1_2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CtUsPl11IcV1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, db_column='Category', max_length=100, null=True)),
                ('subcategory', models.CharField(blank=True, db_column='SubCategory', max_length=100, null=True)),
                ('monyy', models.DateField(blank=True, db_column='MonYY', null=True)),
                ('comp', models.CharField(blank=True, max_length=6, null=True)),
                ('total', models.FloatField(blank=True, db_column='Total', null=True)),
            ],
            options={
                'db_table': 'CT_US_PL_11_IC_V1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CtUsPl1Quantity1V',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('val', models.CharField(blank=True, max_length=1000, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('monyy', models.CharField(blank=True, max_length=6, null=True)),
                ('bottles', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CT_US_PL_1_Quantity1_V',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CtUsPl1Quantity2V',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(blank=True, max_length=20, null=True)),
                ('sid', models.IntegerField(blank=True, null=True)),
                ('val', models.CharField(blank=True, max_length=1000, null=True)),
                ('btls', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CT_US_PL_1_Quantity2_V',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CtUsPl2GrossDiscount1V',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('val', models.CharField(blank=True, max_length=1000, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('monyy', models.CharField(blank=True, max_length=6, null=True)),
                ('gross_discount', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CT_US_PL_2_gross_Discount1_V',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CtUsPl2GrossDiscount2V',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('val', models.CharField(blank=True, max_length=1000, null=True)),
                ('comp', models.CharField(max_length=6)),
                ('grossdis', models.FloatField(blank=True, db_column='grossDis', null=True)),
            ],
            options={
                'db_table': 'CT_US_PL_2_gross_discount2_V',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CtUsPl2GrossRevenue1V',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('val', models.CharField(blank=True, max_length=1000, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('monyy', models.DateField(blank=True, null=True)),
                ('gross_revenue', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CT_US_PL_2_gross_revenue1_V',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CtUsPl2GrossRevenue2V',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('val', models.CharField(blank=True, max_length=1000, null=True)),
                ('comp', models.CharField(max_length=6)),
                ('btls', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CT_US_PL_2_gross_revenue2_V',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CtUsPl3GrossDiscount1V',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('val', models.CharField(blank=True, max_length=1000, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('monyy', models.DateField(blank=True, null=True)),
                ('gross_discount', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CT_US_PL_3_gross_discount1_V',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CtUsPl3GrossDiscount2V',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('val', models.CharField(blank=True, max_length=1000, null=True)),
                ('comp', models.CharField(max_length=6)),
                ('grossdis', models.FloatField(blank=True, db_column='grossDis', null=True)),
            ],
            options={
                'db_table': 'CT_US_PL_3_gross_discount2_V',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CtUsPl4Cogs1V',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField(blank=True, null=True)),
                ('val', models.CharField(blank=True, max_length=1000, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('monyy', models.DateField(blank=True, null=True)),
                ('cogs', models.FloatField(blank=True, db_column='COGS', null=True)),
            ],
            options={
                'db_table': 'CT_US_PL_4_COGS1_V',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CtUsPl4Cogs2V',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField(blank=True, null=True)),
                ('comp', models.CharField(blank=True, max_length=20, null=True)),
                ('fgid', models.IntegerField(blank=True, null=True)),
                ('val', models.CharField(blank=True, max_length=1000, null=True)),
                ('cogs', models.FloatField(blank=True, db_column='COGS', null=True)),
            ],
            options={
                'db_table': 'CT_US_PL_4_COGS2_V',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CtUsPl4CogsCustomV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField(blank=True, null=True)),
                ('val', models.CharField(blank=True, max_length=1000, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('monyy', models.DateField(blank=True, null=True)),
                ('cogs_customs', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CT_US_PL_4_COGS_Custom_V',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CtUsPl4CogsLogisticsV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField(blank=True, null=True)),
                ('val', models.CharField(blank=True, max_length=1000, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('monyy', models.DateField(blank=True, null=True)),
                ('cogs_logistics', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CT_US_PL_4_cogs_logistics_V',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CtUsPl4CogsMonV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField(blank=True, null=True)),
                ('val', models.CharField(blank=True, max_length=1000, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('monyy', models.DateField(blank=True, null=True)),
                ('cogs', models.FloatField(blank=True, db_column='COGS', null=True)),
            ],
            options={
                'db_table': 'CT_US_PL_4_COGS_MON_V',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CtUsPl6Log1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('date2', models.DateField(blank=True, db_column='Date2', null=True)),
                ('total', models.FloatField(blank=True, db_column='Total', null=True)),
            ],
            options={
                'db_table': 'CT_US_PL_6_log_1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CtUsPl6Log2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CT_US_PL_6_log_2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CtUsPnl0V',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField(blank=True, db_column='SID', null=True)),
                ('cat', models.CharField(blank=True, max_length=50, null=True)),
                ('sub_cat', models.CharField(blank=True, db_column='Sub_cat', max_length=200, null=True)),
                ('month', models.IntegerField(blank=True, db_column='MONTH', null=True)),
                ('monyy', models.CharField(blank=True, max_length=6, null=True)),
                ('val', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'db_table': 'ct_US_PnL_0_v',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CtUsPnl9ForexV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_cost_heads', models.CharField(blank=True, db_column='_cost_Heads', max_length=100, null=True)),
                ('monyy', models.CharField(blank=True, db_column='MonYY', max_length=6, null=True)),
                ('total', models.FloatField(blank=True, db_column='Total', null=True)),
            ],
            options={
                'db_table': 'CT_US_PnL_9_Forex_v',
                'managed': False,
            },
        ),
    ]
