# Generated by Django 5.0.6 on 2024-07-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_standalone', '0002_bs2invbalancepurchase_bs3otherassetsliabilitiesv_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AZRB_Guide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_of_sheet', models.CharField(max_length=50)),
                ('short_instruction', models.TextField()),
            ],
            options={
                'db_table': 'AZRB_Guide',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BAL_Guide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_of_sheet', models.CharField(max_length=50)),
                ('short_instruction', models.TextField()),
            ],
            options={
                'db_table': 'BAL_Guide',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IDSBorjomi_Guide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_of_sheet', models.CharField(max_length=50)),
                ('short_instruction', models.TextField()),
            ],
            options={
                'db_table': 'IDSBorjomi_Guide',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KZ_Guide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_of_sheet', models.CharField(max_length=50)),
                ('short_instruction', models.TextField()),
            ],
            options={
                'db_table': 'KZ_Guide',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='USA_Guide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_of_sheet', models.CharField(max_length=50)),
                ('short_instruction', models.TextField()),
            ],
            options={
                'db_table': 'USA_Guide',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UZ_Guide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_of_sheet', models.CharField(max_length=50)),
                ('short_instruction', models.TextField()),
            ],
            options={
                'db_table': 'UZ_Guide',
                'managed': False,
            },
        ),
    ]
