# Generated by Django 5.0.6 on 2024-08-06 11:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('User', 'User'), ('Manager', 'Manager')], max_length=50)),
                ('department', models.CharField(choices=[('HR', 'Human Resources'), ('IT', 'Information Technology'), ('Finance', 'Finance')], max_length=50)),
                ('entity_name', models.CharField(max_length=100)),
                ('cluster_name', models.CharField(max_length=100)),
                ('part_of_group_reporting', models.BooleanField(default=False)),
                ('permissions', models.CharField(choices=[('read', 'Read'), ('write', 'Write'), ('execute', 'Execute')], default='read', max_length=10)),
                ('password', models.CharField(default='PLACEHOLDER_DEFAULT_PASSWORD', max_length=128)),
                ('activation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('activation_end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(default=1)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'UserDetail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userpermissionlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=254, null=True)),
                ('permissions', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'UserPermissionLog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
    ]
