# Generated by Django 5.0.6 on 2024-06-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aje_number', models.IntegerField(blank=True, db_column='AJE_Number', null=True)),
                ('description', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Description', max_length=255, null=True)),
                ('year', models.IntegerField(blank=True, db_column='Year', null=True)),
                ('period', models.IntegerField(blank=True, db_column='Period', null=True)),
                ('cluster', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Cluster', max_length=50, null=True)),
                ('dr_cr', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='DR_CR', max_length=10, null=True)),
                ('bs_pl', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='BS_PL', max_length=10, null=True)),
                ('line', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Line', max_length=50, null=True)),
                ('decomposition1', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Decomposition1', max_length=255, null=True)),
                ('decomposition2', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Decomposition2', max_length=255, null=True)),
                ('amount_in_usd', models.DecimalField(blank=True, db_column='Amount_in_USD', decimal_places=2, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'EJE',
                'managed': False,
            },
        ),
    ]
