# Generated by Django 5.0.6 on 2024-07-31 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adjustment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, max_length=255, null=True)),
                ('cluster', models.CharField(blank=True, max_length=255, null=True)),
                ('entity', models.CharField(blank=True, max_length=255, null=True)),
                ('CompanyType', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'EntityAdjustments',
                'managed': False,
            },
        ),
    ]
