# Generated by Django 5.0.6 on 2024-05-15 13:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='c_app_db',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('Apps', models.CharField(max_length=255)),
                ('DB_name', models.CharField(max_length=255)),
                ('Update_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'c_app_db',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='c_extr_table_cols',
            fields=[
                ('SID', models.AutoField(primary_key=True, serialize=False)),
                ('Jurisdiction', models.CharField(max_length=100)),
                ('AcctSytesm', models.CharField(max_length=100)),
                ('Src_Host', models.CharField(max_length=100)),
                ('Src_DB_Name', models.CharField(max_length=100)),
                ('Src_Port', models.CharField(max_length=100)),
                ('Src_Tables', models.CharField(max_length=100)),
                ('Src_Columns', models.CharField(max_length=1000)),
                ('Src_UPDATE_TIME', models.DateTimeField(default=django.utils.timezone.now)),
                ('src_type', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'c_extr_table_cols',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='c_extr_tables',
            fields=[
                ('SID', models.AutoField(primary_key=True, serialize=False)),
                ('Jurisdiction', models.CharField(max_length=100)),
                ('AcctSytesm', models.CharField(max_length=100)),
                ('Src_Host', models.CharField(max_length=100)),
                ('Src_DB_Name', models.CharField(max_length=100)),
                ('Src_Port', models.CharField(max_length=100)),
                ('Src_Tables', models.CharField(max_length=100)),
                ('Src_UPDATE_TIME', models.DateTimeField(default=django.utils.timezone.now)),
                ('src_type', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'c_extr_tables',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ce_mapng',
            fields=[
                ('SID', models.AutoField(primary_key=True, serialize=False)),
                ('jusrisdiction', models.CharField(max_length=100)),
                ('src_type', models.CharField(max_length=100)),
                ('src_tblnm', models.CharField(max_length=100)),
                ('tgt_tblnm', models.CharField(max_length=100)),
                ('tgt_tblcols', models.CharField(max_length=100)),
                ('mapng_nm', models.CharField(max_length=100)),
                ('mpngtxt', models.CharField(max_length=100)),
                ('insrt_TIMESTAMP', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ce_mapng',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SourceConn',
            fields=[
                ('SID', models.AutoField(primary_key=True, serialize=False)),
                ('Jurisdiction', models.CharField(max_length=100)),
                ('DATABASES', models.CharField(max_length=100)),
                ('Src_DB_NAME', models.CharField(max_length=100)),
                ('Src_USER_NAME', models.CharField(max_length=100)),
                ('Src_PASSWRD', models.CharField(max_length=100)),
                ('Src_HOST', models.CharField(max_length=100)),
                ('Src_PORT', models.IntegerField()),
                ('Src_UPDATE_TIME', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'SourceConn',
                'managed': False,
            },
        ),
    ]
