# Generated by Django 5.0.6 on 2024-08-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=100)),
                ('period', models.DateField()),
                ('line_l1', models.CharField(max_length=100)),
                ('line_l2', models.CharField(max_length=100)),
                ('line_l3', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
                ('dlm', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'PnLByEntity',
                'managed': False,
            },
        ),
    ]
